package org.jbpm.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Richiesta  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String fromStore;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer numDipendenti;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String requestName;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String store;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String toStore;

    public Richiesta() {
    }

    public Richiesta(java.lang.String requestName, java.lang.String store, java.lang.Integer numDipendenti, java.lang.String fromStore, java.lang.String toStore) {
        this.requestName = requestName;
        this.store = store;
        this.numDipendenti = numDipendenti;
        this.fromStore = fromStore;
        this.toStore = toStore;
    }


    
    public java.lang.String getFromStore() {
        return this.fromStore;
    }

    public void setFromStore(  java.lang.String fromStore ) {
        this.fromStore = fromStore;
    }
    
    public java.lang.Integer getNumDipendenti() {
        return this.numDipendenti;
    }

    public void setNumDipendenti(  java.lang.Integer numDipendenti ) {
        this.numDipendenti = numDipendenti;
    }
    
    public java.lang.String getRequestName() {
        return this.requestName;
    }

    public void setRequestName(  java.lang.String requestName ) {
        this.requestName = requestName;
    }
    
    public java.lang.String getStore() {
        return this.store;
    }

    public void setStore(  java.lang.String store ) {
        this.store = store;
    }
    
    public java.lang.String getToStore() {
        return this.toStore;
    }

    public void setToStore(  java.lang.String toStore ) {
        this.toStore = toStore;
    }
}